[project]
name = "claude"
version = "0.1.0"
description = "Claude Code"
authors = [
    {name = "sriramachandramanjunatha",email = "sriramachandramanjunatha@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-dotenv (>=1.2.3,<2.0.0)",
    "openai (>=3.19.0,<4.0.0)",
    "chromadb (>=1.5.9,<2.0.0)",
    "rich (>=15.0.0,<16.0.0)",
    "pydantic (>=2.13.5,<3.0.0)",
    "pyyaml (>=6.0.3,<7.0.0)",
    "langchain (>=1.4.2,<2.0.0) ; python_version >= \"3.12\" and python_full_version < \"4.0.0\"",
    "langchain-openai (>=1.6.4,<2.0.0) ; python_version >= \"3.12\" and python_full_version < \"4.0.0\"",
    "langchain-anthropic (>=1.7.3,<2.0.0) ; python_version >= \"3.12\" and python_full_version < \"4.0.0\"",
    "langchain-huggingface (>=1.2.2,<2.0.0) ; python_version >= \"3.12\" and python_full_version < \"4.0.0\"",
    "tree-sitter (>=0.26.0,<0.27.0)",
    "tree-sitter-language-pack (>=1.20.0,<2.0.0)",
    "truststore (>=0.10.4,<0.11.0)"
]

[tool.poetry]
packages = [{include = "claude"}]


[tool.poetry.scripts]
claude = "claude.main:run"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
